version: "3.8"

services:
  db_mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - 8001:8000
    depends_on:
      - db_mysql
    env_file: 
      - ./.env
