# Generated by Django 5.1.1 on 2024-12-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.JSONField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('rango_edad', models.CharField(max_length=50)),
                ('nivel_educacion', models.CharField(max_length=50)),
                ('titulo_relacionado', models.PositiveIntegerField(default=1)),
                ('cursos_pedagogicos', models.BooleanField()),
                ('reconocimientos_academicos', models.BooleanField()),
                ('preferencias_asignaturas', models.TextField()),
                ('metodologias_ensenanza', models.TextField()),
                ('acepta_sistema_recomendacion', models.PositiveIntegerField(default=1)),
                ('materias_impartidas', models.TextField()),
                ('veces_impartidas', models.PositiveIntegerField(default=0)),
                ('materias_no_relacionadas', models.PositiveIntegerField(default=1)),
                ('desacuerdo_con_materias', models.PositiveIntegerField(default=1)),
                ('conoce_sistemas_recomendacion', models.PositiveIntegerField(default=1)),
                ('cree_en_sistemas_recomendacion', models.PositiveIntegerField(default=1)),
                ('acepta_implementacion', models.PositiveIntegerField(default=1)),
                ('introduccion_familiaridad_conceptos_basicos', models.PositiveIntegerField(default=1)),
                ('introduccion_grado_academico_software', models.PositiveIntegerField(default=1)),
                ('proceso_software_introduccion_resolucion_problemas', models.PositiveIntegerField(default=1)),
                ('proceso_software_procesos_software', models.PositiveIntegerField(default=1)),
                ('proceso_software_normativas_internacionales', models.PositiveIntegerField(default=1)),
                ('proceso_software_publicaciones_investigacion', models.PositiveIntegerField(default=1)),
                ('ing_requerimientos_participacion_proyectos', models.PositiveIntegerField(default=1)),
                ('ing_requerimientos_tecnicas_requerimientos', models.PositiveIntegerField(default=1)),
                ('ing_requerimientos_interaccion_equipos', models.PositiveIntegerField(default=1)),
                ('model_software_familiaridad_uml', models.PositiveIntegerField(default=1)),
                ('model_software_herramientas_diseno', models.PositiveIntegerField(default=1)),
                ('model_software_modelado_proyectos', models.PositiveIntegerField(default=1)),
                ('dise_arqui_software_diseno_arquitecturas', models.PositiveIntegerField(default=1)),
                ('dise_arqui_software_patrones_arquitectura', models.PositiveIntegerField(default=1)),
                ('dise_arqui_software_elegir_arquitecturas', models.PositiveIntegerField(default=1)),
                ('hombre_maquina_diseno_gui', models.PositiveIntegerField(default=1)),
                ('hombre_maquina_principios_usabilidad', models.PositiveIntegerField(default=1)),
                ('hombre_maquina_herramientas_gui', models.PositiveIntegerField(default=1)),
                ('construccion_software_experiencia_lenguajes', models.PositiveIntegerField(default=1)),
                ('construccion_software_metodologias_agiles', models.PositiveIntegerField(default=1)),
                ('construccion_software_buenas_practicas', models.PositiveIntegerField(default=1)),
                ('experiencia_usuario_diseno_interfaces', models.PositiveIntegerField(default=1)),
                ('experiencia_usuario_pruebas_usabilidad', models.PositiveIntegerField(default=1)),
                ('experiencia_usuario_psicologia_cognitiva', models.PositiveIntegerField(default=1)),
                ('calidad_software_pruebas_software', models.PositiveIntegerField(default=1)),
                ('calidad_software_automatizacion_pruebas', models.PositiveIntegerField(default=1)),
                ('calidad_software_modelos_calidad', models.PositiveIntegerField(default=1)),
                ('validacion_software_control_versiones', models.PositiveIntegerField(default=1)),
                ('validacion_software_integracion_continua', models.PositiveIntegerField(default=1)),
                ('validacion_software_herramientas_configuracion', models.PositiveIntegerField(default=1)),
                ('configuracion_software_herramienta_control_versiones', models.PositiveIntegerField(default=1)),
                ('configuracion_software_gestion_cambios', models.PositiveIntegerField(default=1)),
                ('configuracion_software_gestion_configuracion', models.PositiveIntegerField(default=1)),
                ('auditoria_software_normativas_auditoria', models.PositiveIntegerField(default=1)),
                ('auditoria_software_auditorias_software', models.PositiveIntegerField(default=1)),
                ('auditoria_software_analisis_critico', models.PositiveIntegerField(default=1)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.profesor')),
            ],
        ),
    ]
